targets:
  $default:
    builders:
      drift_dev:
        options:
          # 数据库模型的生成选项
          apply_converters_on_variables: true
          write_from_json_string_constructor: true
          
      # 配置json_serializable生成器
      json_serializable:
        options:
          # 必须启用显式的toJson方法
          explicit_to_json: true
          include_if_null: false 